### ISSUE TITLE
Query Regarding the Number of Subjects for 5-min vs. 10-min Data Trimming

### ISSUE THREAD

**Issue by fullcream9** [ABCD-STUDY/nda-abcd-collection-3165#64] opened 2023-10-23 06:14 UTC
Hello all,

I'm trying to get a clear understanding of the trimming conditions for data based on FD 0.2 restrictions. My interpretation is that the condition requires the data to satisfy the FD 0.2 threshold and, at the same time, have a duration where the subject satisfies the FD 0.2 restriction for more than 5 minutes.

However, I've come across an observation that I find puzzling. The dataset labeled _ses-baselineYear1Arm1_task-rest_bold_atlas-Gordon2014FreeSurferSubcortical_desc-filtered_timeseries_thresh-fd0p2mm_censor-10min_conndata-network_connectivity.pconn.nii has more subjects than the dataset labeled _ses-baselineYear1Arm1_task-rest_bold_atlas-Gordon2014FreeSurferSubcortical_desc-filtered_timeseries_thresh-fd0p2mm_censor-5min_conndata-network_connectivity.pconn.nii. Specifically, there are 577 subjects in the 5-minute dataset and 609 subjects in the 10-minute dataset.

Can someone shed some light on why the 10-minute dataset has more subjects than the 5-minute dataset? It seems counterintuitive.

Thanks in advance for your insights!

**Comment by LuciMoore** [comment] 2024-08-20 17:25
@tjhendrickson can you check in on this for the new release?

**Comment by LuciMoore** [comment] 2024-08-27 19:21
This will be resolved in upcoming release. The original mistake was caused by there not being all subjects uploaded for the 5 min data group

**Closed as completed by LuciMoore** 2024-08-27 19:21 UTC
